config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)


    if @post.save
      redirect_to @post
    else
      # Allows to retain written blog post if error
      render 'new'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit([:title, :body]))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path

  end


  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment_content
    %p.comment_name
      %strong= comment.name
    %p.comment_body= comment.body
    %p.comment_time
      = time_ago_in_words(comment.created_at)
      Ago
  - if user_signed_in?
    %p= link_to 'Delete', [comment.post, comment], |
        method: :delete,                           |
        class: "button",                           |
        data: { confirm: 'Are you sure?' }         |

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|
  = f.label :name
  %br/
  = f.text_field :name
  %br/
  %br/
  = f.label :body
  %br/
  = f.text_area :body
  %br/
  %br/
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bloog!
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Kalam'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
  %body
    #sidebar
      -##logo
      -#  = link_to root_path do
      -#    = image_tag "logo.svg"
      %ul
        %li.category Linky Links
        %li= link_to "Bloog Posts", root_path
        %li= link_to "Aboot Mee", about_path
      %ul
        %li.category Sosho Links
        %li
          %a{:href => "https://twitter.com/HelloDuy"} Tweeter
        %li
          %a{:href => "https://github.com/DuyH"} Gethoob
        %li
          %a{:href => "mailto:dhuynh88@uw.edu"} Emale
      - unless user_signed_in?
        %p.sign_in= link_to "Admin Login", new_user_session_path
    #main_content
      #header
        - if current_page?(root_path)
          %p=link_to 'Bloog', root_path
        - elsif current_page?(about_path)
          %p About
        - else
          = link_to "Back to All Bloog Posts", root_path
        - if user_signed_in?
          .buttons
            %button.button= link_to "New Post", new_post_path
            %button.button= link_to 'Log Out',destroy_user_session_path, method: :delete
        - else
          .buttons
            %button.button= link_to 'Sign Up', new_user_registration_path
            %button.button= link_to 'Sign In', new_user_session_path
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert")
      = yield

app/views/pages/about.html.haml
#page_wrapper
  #profile_image
    = image_tag "profile.jpeg"
  #content
    %h1 I'm Duy. It's pronounced U-E.
    %p This is one of 9 apps I'm building this quarter for TCSS 498, Direct Readings. Woohoo!

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #errors
      %h2
        = pluralize(@post.errors.count, "error")
        prevented this post from saving:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  = f.label :title
  %br/
  = f.text_field :title
  %br/
  %br/
  = f.label :body
  %br/
  = f.text_area :body
  %br/
  %br/
  = f.submit

app/views/posts/edit.html.haml
#page_wrapper
  %h1 Edit Post
  = render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  .post_wrapper
    %h2.title= link_to post.title, post
    %p.date= post.created_at.strftime("%B %d, %Y")

app/views/posts/new.html.haml
#page_wrapper
  %h1 New Post
  = render 'form'

app/views/posts/show.html.haml
#post_content
  %h1.title= @post.title
  %p.date
    Submitted #{time_ago_in_words(@post.created_at)} Ago
    - if user_signed_in?
      |
      =link_to 'Edit', edit_post_path(@post)
      |
      =link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }
  %p.body= @post.body
  #comments
    %h2
      = @post.comments.count
      Comments
    = render @post.comments
    %h3 Add a comment:
    = render "comments/form"